services:
  nestjs:
    container_name: nestjs
    image: nestjs:1.0.4
    build:
      context: .
      dockerfile: DockerFile
    restart: unless-stopped
    ports:
      - 3000:3000
    command: ' node ./dist/main.js'
    depends_on:
      nestjs:
        condition: service_healthy
    healthcheck:
      test: 'curl http://localhost:3000/'
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
